### PR TITLE
Update go-hibp with breaking changes

### PR DESCRIPTION
**Pull request by wneessen**
This PR updates go-hibp to v1.0.4.

The underlying library https://github.com/wneessen/go-hibp has just been updated to v1.0.4, which introduced some breaking changes (see: https://github.com/wneessen/go-hibp/releases/tag/v1.0.4). Since I knew this module uses go-hibp, I've updated the changes accordingly.

### CODE REVIEW

**Comment by misraved** [comment]
Apologies for the delay @wneessen and many thanks for raising this PR. I took a look at the changes and they look good.

The method nomenclature is the biggest change and the underlying functionality hasn't changed (so that's good news 👍).

Did you encounter any issues while running the queries?

**Comment by wneessen** [comment]
I stand myself corrected. During some further local testing I found an error within the checking of the given full hash value.  

Previously `strconv.ParseUint` was used to validate if a given full SHA1 hash is valid. Since the nature of SHA1 this hash could easily exceed the range of Uint and therefore is not a good solution to make sure a hash is valid hex notation.

The result was the `'hash' is not a valid SHA-1 hash (SQLSTATE HV000)` error even though the given hash was valid.

Instead, we now use `hex.Decode` which is meant for this kind of tasks and will not fail anymore if a given hash is bigger than the Uint limit.

This is unrelated to the go-hibp update and was already present before. But I've also created a fix for this bug and pushed it to this PR.

**Comment by misraved** [comment]
Thank you @wneessen for the quick turnaround on the feedback and for fixing a preexisting bug 👍 .

I will give it one final look and run a few queries to ensure we don't have regressions before we push for a release 👍.

**Comment by misraved** [comment]
Apologies @wneessen, I merged in a PR - https://github.com/turbot/steampipe-plugin-hibp/pull/7 which has created the merge conflict.

Could you please resolve the merge conflict? sorry for the trouble 😢 .

**Comment by wneessen** [comment]
> Could you please resolve the merge conflict? sorry for the trouble 😢 .
> 
Conflict resolved

**Comment by misraved** [comment]
Thanks a lot @wneessen for making the changes 👍 . I tested out the queries and they run fine 😄 .

Great work 🎉 .

**Pull request merged**
